[project]
name = "Twitter Previews Discord Bot"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE.txt"}
authors = [
  {name = "Miguel Sousa"}
]
maintainers = [
  {name = "Miguel Sousa"}
]